version: 2
updates:
  # ルートディレクトリのパッケージの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    
  # Webアプリケーションの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps-web)"
      include: "scope"
      
  # Workersアプリケーションの依存関係を管理
  - package-ecosystem: "npm"
    directory: "/apps/workers"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(deps-workers)"
      include: "scope"
    
  # GitHub Actionsの依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(actions)"
      prefix-development: "chore(actions)"
      include: "scope"