version: 2
updates:
  # ルートディレクトリのパッケージの依存関係を管理（モノレポ管理ツールのみ）
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      monorepo-tools:
        patterns:
          - "@biomejs/biome"
          - "turbo"
        update-types:
          - "minor"
          - "patch"
      testing-tools:
        patterns:
          - "@cloudflare/vitest-pool-workers"
          - "@vitest/coverage-istanbul"
          - "@vitest/ui"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps-root)"
      include: "scope"
    
  # Webアプリケーション - 依存関係
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      # radix-ui関連パッケージを専用グループで管理
      radix-ui:
        patterns:
          - "@radix-ui/*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "@auth/core"
          - "@hookform/resolvers"
          - "class-variance-authority"
          - "clsx"
          - "cmdk"
          - "date-fns"
          - "embla-carousel-react"
          - "input-otp"
          - "lucide-react"
          - "next"
          - "next-auth"
          - "next-themes"
          - "react"
          - "react-dom"
          - "react-hook-form"
          - "react-resizable-panels"
          - "recharts"
          - "sonner"
          - "tailwind-merge"
          - "vaul"
          - "zod"
      development-dependencies:
        patterns:
          - "@cloudflare/workers-types"
          - "@opennextjs/cloudflare"
          - "@tailwindcss/postcss"
          - "@types/*"
          - "tailwindcss"
          - "tw-animate-css"
          - "typescript"
          - "vitest"
          - "wrangler"
    commit-message:
      prefix: "chore(deps-web)"
      include: "scope"
      
  # Workersアプリケーション - 依存関係
  - package-ecosystem: "npm"
    directory: "/apps/workers"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    groups:
      production-dependencies:
        patterns:
          - "@hono/zod-validator"
          - "drizzle-orm"
          - "hono"
          - "uuid"
          - "zod"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        patterns:
          - "@hono/vite-build"
          - "@types/*"
          - "drizzle-kit"
          - "miniflare"
          - "typescript"
          - "vite"
          - "wrangler"
        update-types:
          - "minor"
          - "patch"
      testing-dependencies:
        patterns:
          - "@cloudflare/vitest-pool-workers"
          - "@vitest/coverage-istanbul"
          - "@vitest/coverage-v8"
          - "vitest"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore(deps-workers)"
      include: "scope"
    
  # GitHub Actionsの依存関係を管理
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    commit-message:
      prefix: "chore(actions)"
      prefix-development: "chore(actions)"
      include: "scope"