services:
  app:
    container_name: app
    image: bref/php-83-fpm-dev:2
    ports:
      - '8000:8000'
    volumes:
      - ./server:/var/task:ro
      - ./server/storage:/tmp/storage
    environment:
      HANDLER: public/index.php
    depends_on:
      - db
      - mailhog
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
