import "./globals.css";
import AuthProvider from "@/contexts/auth-provider";
import type { Metadata } from "next";

const geistSans = {
	variable: "--font-geist-sans",
};

const geistMono = {
	variable: "--font-geist-mono",
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	// ダークテーマ対応を拒否する設定
	colorScheme: "light",
	themeColor: [{ media: "(prefers-color-scheme: light)", color: "white" }],
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// lang属性を日本語に変更し、light強制のためのclassを追加
		<html lang="ja" className="light">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	);
}
