// Next.jsの型定義
type Metadata = {
	title?: string;
	description?: string;
	[key: string]: unknown;
};

import "./globals.css";

const geistSans = {
	variable: "--font-geist-sans",
};

const geistMono = {
	variable: "--font-geist-mono",
};

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
