// Generated by Wrangler on Wed Aug 07 2024 07:41:26 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	API_URL: "https://0l6fmkfqsd.execute-api.ap-northeast-1.amazonaws.com/prod/";
	USER_URL: "https://dojo-pass.pages.dev/";
}
