// Generated by Wrangler on Wed Aug 07 2024 08:18:28 GMT+0900 (Japan Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	API_URL: "https://0l6fmkfqsd.execute-api.ap-northeast-1.amazonaws.com/prod/";
}
