name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - id: get-packages
        name: Get Packages
        run: |
          PACKAGES=$(ls -d apps/* | jq -R -s .)
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

  test:
    name: Test ${{ matrix.package }}
    needs: setup
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.setup.outputs.packages) }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      # Turboレポをキャッシュ
      # キャッシュを介した高速化

      - name: Run tests
        run: pnpm --filter=${{ matrix.package }} test

      - name: Upload test coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-reports-${{ matrix.package }}
          path: |
            ${{ matrix.package }}/coverage/
            ${{ matrix.package }}/coverage-results/
          retention-days: 14

  upload-coverage:
    name: Upload Combined Coverage Reports
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download all artifacts
        uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427 # v4.1.4
        with:
          path: artifacts
          pattern: coverage-reports-*
          merge-multiple: true

      - name: Combine coverage reports
        run: |
          mkdir -p coverage-combined
          cp -r artifacts/* coverage-combined/ || true

      - name: Upload combined coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-reports
          path: coverage-combined
          retention-days: 14
