name: Test

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/test.yaml'      # 自身のワークフローファイル
      # テスト関連ファイル
      - '**/__tests__/**'                  # テストファイル
      - '**/test/**'                       # テストディレクトリ
      - '**/*.test.ts'                     # テストファイル
      - '**/*.test.tsx'                    # Reactテストファイル
      - '**/*.test.js'                     # JSテストファイル
      - '**/*.test.jsx'                    # React JSテストファイル
      - '**/*.spec.ts'                     # テストファイル
      - '**/*.spec.tsx'                    # Reactテストファイル
      # テスト設定
      - '**/vitest.config.*'               # Vitest設定ファイル
      - '**/jest.config.*'                 # Jest設定ファイル
      - 'vitest.workspace.ts'              # Vitest ワークスペース設定
      # ソースコード（テスト対象）
      - 'apps/*/src/**/*.ts'               # アプリのソースコード
      - 'apps/*/src/**/*.tsx'              # アプリのReactコード
      - 'packages/*/src/**/*.ts'           # パッケージのソースコード
      - 'packages/*/src/**/*.tsx'          # パッケージのReactコード
      # 共通設定
      - 'package.json'                     # ルートパッケージ設定
      - 'pnpm-lock.yaml'                   # 依存関係ロックファイル
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/test.yaml'      # 自身のワークフローファイル
      # テスト関連ファイル
      - '**/__tests__/**'                  # テストファイル
      - '**/test/**'                       # テストディレクトリ
      - '**/*.test.ts'                     # テストファイル
      - '**/*.test.tsx'                    # Reactテストファイル
      - '**/*.test.js'                     # JSテストファイル
      - '**/*.test.jsx'                    # React JSテストファイル
      - '**/*.spec.ts'                     # テストファイル
      - '**/*.spec.tsx'                    # Reactテストファイル
      # テスト設定
      - '**/vitest.config.*'               # Vitest設定ファイル
      - '**/jest.config.*'                 # Jest設定ファイル
      - 'vitest.workspace.ts'              # Vitest ワークスペース設定
      # ソースコード（テスト対象）
      - 'apps/*/src/**/*.ts'               # アプリのソースコード
      - 'apps/*/src/**/*.tsx'              # アプリのReactコード
      - 'packages/*/src/**/*.ts'           # パッケージのソースコード
      - 'packages/*/src/**/*.tsx'          # パッケージのReactコード
      # 共通設定
      - 'package.json'                     # ルートパッケージ設定
      - 'pnpm-lock.yaml'                   # 依存関係ロックファイル

# 同一PRの古いジョブを自動的にキャンセルする設定
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - id: get-packages
        name: Get Packages
        run: |
          echo "packages=[\"apps/web\",\"apps/workers\"]" >> $GITHUB_OUTPUT

  test:
    name: Test ${{ matrix.package }}
    needs: setup
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.setup.outputs.packages) }}

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # Turboレポをキャッシュ
      # キャッシュを介した高速化

      - name: Run tests
        run: pnpm --filter=${{ matrix.package }} test

      - name: Generate test coverage
        run: pnpm --filter=${{ matrix.package }} test:coverage

      - name: Upload test coverage reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: coverage-reports-${{ matrix.package }}
          path: |
            ${{ matrix.package }}/coverage/
          retention-days: 14
