name: Web App CI

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/web.yaml'      # 自身のワークフローファイル
      - 'apps/web/**'                     # webアプリのソースコード全体
      - 'biome.json'                      # Biome設定
      - 'lefthook.yml'                    # Lefthook設定
      - 'config/biome/**'                 # Biome設定ディレクトリ
      - 'package.json'                    # ルートパッケージ設定
      - 'pnpm-workspace.yaml'             # PNPM ワークスペース設定
      - 'tsconfig.base.json'              # ベースTypeScript設定
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/web.yaml'      # 自身のワークフローファイル
      - 'apps/web/**'                     # webアプリのソースコード全体
      - 'biome.json'                      # Biome設定
      - 'lefthook.yml'                    # Lefthook設定
      - 'config/biome/**'                 # Biome設定ディレクトリ
      - 'package.json'                    # ルートパッケージ設定
      - 'pnpm-workspace.yaml'             # PNPM ワークスペース設定
      - 'tsconfig.base.json'              # ベースTypeScript設定

# 同一PRの古いジョブを自動的にキャンセルする設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # テストのみのジョブ（push・PRの両方で実行）
  web-test:
    name: Web App Test
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test with Coverage
        run: pnpm --filter=web test:coverage

      - name: Comment Coverage on PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f apps/web/coverage/coverage-summary.json ]; then
            # カバレッジデータを抽出
            TOTAL_LINES=$(jq -r '.total.lines.pct' apps/web/coverage/coverage-summary.json)
            TOTAL_STATEMENTS=$(jq -r '.total.statements.pct' apps/web/coverage/coverage-summary.json)
            TOTAL_FUNCTIONS=$(jq -r '.total.functions.pct' apps/web/coverage/coverage-summary.json)
            TOTAL_BRANCHES=$(jq -r '.total.branches.pct' apps/web/coverage/coverage-summary.json)
            
            # PRコメント作成
            COMMENT="## 📊 Web App Test Coverage Report
            
            | Metric | Coverage |
            |--------|----------|
            | Lines | ${TOTAL_LINES}% |
            | Statements | ${TOTAL_STATEMENTS}% |
            | Functions | ${TOTAL_FUNCTIONS}% |
            | Branches | ${TOTAL_BRANCHES}% |
            
            Generated on: $(date)"
            
            # PRにコメント投稿
            gh pr comment ${{ github.event.number }} --body "$COMMENT"
          else
            echo "Coverage summary file not found"
          fi

  # Lint・Format・TypeCheckのジョブ（PRのみ実行）
  web-lint:
    name: Web App Lint & Format & TypeCheck
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm --filter=web lint

      - name: Format Check
        run: pnpm --filter=web format

      - name: Type Check
        run: pnpm --filter=web typecheck

