name: Web App CI

on:
  push:
    branches: ["main"]
    paths:
      - '.github/workflows/web.yaml'      # 自身のワークフローファイル
      - 'apps/web/**'                     # webアプリのソースコード全体
      - 'biome.json'                      # Biome設定
      - 'lefthook.yml'                    # Lefthook設定
      - 'config/biome/**'                 # Biome設定ディレクトリ
      - 'package.json'                    # ルートパッケージ設定
      - 'pnpm-workspace.yaml'             # PNPM ワークスペース設定
      - 'tsconfig.base.json'              # ベースTypeScript設定
  pull_request:
    branches: ["main"]
    paths:
      - '.github/workflows/web.yaml'      # 自身のワークフローファイル
      - 'apps/web/**'                     # webアプリのソースコード全体
      - 'biome.json'                      # Biome設定
      - 'lefthook.yml'                    # Lefthook設定
      - 'config/biome/**'                 # Biome設定ディレクトリ
      - 'package.json'                    # ルートパッケージ設定
      - 'pnpm-workspace.yaml'             # PNPM ワークスペース設定
      - 'tsconfig.base.json'              # ベースTypeScript設定

# 同一PRの古いジョブを自動的にキャンセルする設定
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # テストのみのジョブ（push・PRの両方で実行）
  web-test:
    name: Web App Test
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Test
        run: pnpm --filter=web test

  # Lint・Format・TypeCheckのジョブ（PRのみ実行）
  web-lint:
    name: Web App Lint & Format & TypeCheck
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Setup Node.js environment
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm --filter=web lint

      - name: Format Check
        run: pnpm --filter=web format

      - name: Type Check
        run: pnpm --filter=web typecheck